# This is a basic workflow to help you get started with Actions

name: Merge  to the main

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
 

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 14, 16, 18, ]

     name: Node ${{ matrix.node }} sample    
    # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Run linting rules and test
        uses: actions/setup-node@v3
        with:
           node-version: ${{ matrix.node }}
      -  run: npm ci
      -  run: npm run lint
      -  run: npm run prettier
      -  run: npm run test
      -  run: npm run build

     
